# Promises Chaining
```
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000); // (*)

}).then(function(result) { // (**)

  alert(result); // 1
  return result * 2;

}).then(function(result) { // (***)

  alert(result); // 2
  return result * 2;

}).then(function(result) {

  alert(result); // 4
  return result * 2;

});
```
- 최초의 Promise는 1초 후에 resolve(1)을 한다.
- 바로 이어지는 .then 핸들러가 불린다 //(**)
- alert(1)을 실행 후, 2를 리턴한다
- 리턴된 값이 이어지는 .then 핸들러에 넘겨진다 //(***)
- alert(2)가 실행되며, 4를 리턴한다.
- 마지막 then으로 값이 넘겨지며, alert(4)를 실행 후, 8을 리턴한다.

### Promise.then returns a promise
- 위의 예제가 then으로 계속 chaining 될 수 있는 이유는, promise.then이 promise를 리턴해서이다.
- then 핸들러가 값을 리턴하면, 그것은 promise이며, 그 다음 then chaining에서 이 promise는 resolved되어, 이어지는 then 핸들러가 값을 사용할 수 있는것이다.

### chaining이 아닌 single promise에 여러개의 .then 핸들러를 이용하는 경우.
```
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve(1), 1000);
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});

promise.then(function(result) {
  alert(result); // 1
  return result * 2;
});
```
- 위의 예제는, 하나의 Promise에 3개의 then 핸들러를 사용하는 경우이다.
- 이것은 chaining이 아니라, 하나의 promise에 여러개의 consumer code를 추가하는 것이므로, 각각의 then핸들러에 들어오는 result값은 모두 1이다.


## Returning promises
- 일반적으로 .then 핸들러로 리턴된 값은 즉시 다음 핸들러에 전달된다.
- 하나의 예외는, return 값이 Promise인 경우이다.
- 이 경우에는, 그 Promise가 settle 될때까지 이어지는 실행은 멈춘다. 그 값이 settle되면 .then 핸들러로 넘겨진다.

```
new Promise(function(resolve, reject) {

  setTimeout(() => resolve(1), 1000);

}).then(function(result) {

  alert(result); // 1

  return new Promise((resolve, reject) => { // (*)
    setTimeout(() => resolve(result * 2), 1000);
  });

}).then(function(result) { // (**)

  alert(result); // 2

  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(result * 2), 1000);
  });

}).then(function(result) {

  alert(result); // 4

});
```
- 위 예제에서 첫번쨰 .then은 1을 리턴받았고, 그 핸들러 안에서 리턴을 promise로 한다.
- 이 경우에는 setTimeout 1초 후에 promise가 settle되어 resolve(2)를 해서 다음 .then 핸들러로 반환한다.

## Bigger example: fetch
- 실제로 프론트앤드 개발을 하다보면, 네트워크 request를 요청할때 promise를 사용하게 된다.
- 이번 예제에서는 리모트 서버로부터 정보를 로딩할때 사용하는 fetch를 사용해본다.
```
let promise = fetch(url);
```
- 위 코드는 url에 해당하는 서버로 네트워크 리퀘스트를 보내고 promise를 반환한다.
- promise는 remove server가 header와함게 반응해줄때 resopnse 객체를 resolve해준다. 그러나 그 response는 full response가 아니다.
- 모든 response를 다 받기 위해서는, response.text() 메소드를 불러야 하고 이것은 리모트서버에서 모든 텍스트를 다운받았을때 promise를 resolve해서 리턴한다.
```
let userId = 'arclien';
fetch(`https://api.github.com/users/${userId}`)
  // .then below runs when the remote server responds
  .then(function(response) {
    // response.text() returns a new promise that resolves with the full response text
    // when we finish downloading it
    return response.text();
  })
  .then(function(text) {
    // ...and here's the content of the remote file
    alert(text);
  });
```
- response.json()을 사용해서, 서버로부터 데이터를 JSON 포멧으로 파싱해서 가져올 수 있다.

```
// same as above, but response.json() parses the remote content as JSON
let userId = 'arclien';
fetch(`https://api.github.com/users/${userId}`)
  .then(response => response.json())
  .then(user => alert(user.login)); // arclien
```

```
let userId = 'arclien';
fetch(`https://api.github.com/users/${userId}`)
  // Load the response as json
  .then(response => response.json())
  // Show the avatar image (githubUser.avatar_url) for 3 seconds (maybe animate it)
  .then(githubUser => {
    let img = document.createElement('img');
    img.src = githubUser.avatar_url;
    img.className = "promise-avatar-example";
    document.body.append(img);

    setTimeout(() => img.remove(), 3000); // (*)
  });
```

## Error handling
- 비동기 액션은 때때로 promise가 reject되는 경우에 fail될 수 있다. 즉, 리모트 서버로부터 fetch를 시도했는데, 해당하는 데이터가 없거나 서버가 반응을 안할 경우이다.
- 이 때는, .catch로 에러를 핸들링해야 한다.

```
fetch('https://no-such-server.blabla') // rejects
  .then(response => response.json())
  .catch(err => alert(err)) // TypeError: failed to fetch (the text may vary)

fetch('/') // fetch works fine now, the server responds successfully
  .then(response => response.json()) // rejects: the page is HTML, not a valid json
  .catch(err => alert(err)) // SyntaxError: Unexpected token < in JSON at position 0
```
